# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OS_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 867)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setObjectName("widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.ram_graph = QtWidgets.QTableWidget(self.widget)
        self.ram_graph.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ram_graph.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.ram_graph.setObjectName("ram_graph")
        self.ram_graph.setColumnCount(0)
        self.ram_graph.setRowCount(0)
        self.ram_graph.horizontalHeader().setVisible(False)
        self.ram_graph.horizontalHeader().setMinimumSectionSize(1)
        self.ram_graph.verticalHeader().setVisible(False)
        self.ram_graph.verticalHeader().setMinimumSectionSize(1)
        self.verticalLayout_8.addWidget(self.ram_graph)
        self.ram_details = QtWidgets.QLabel(self.widget)
        self.ram_details.setText("")
        self.ram_details.setObjectName("ram_details")
        self.verticalLayout_8.addWidget(self.ram_details)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.ram_total = QtWidgets.QLabel(self.widget_2)
        self.ram_total.setText("")
        self.ram_total.setObjectName("ram_total")
        self.gridLayout_2.addWidget(self.ram_total, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.ram_used = QtWidgets.QLabel(self.widget_2)
        self.ram_used.setText("")
        self.ram_used.setObjectName("ram_used")
        self.gridLayout_2.addWidget(self.ram_used, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.groupBox)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.process_shot = QtWidgets.QTableWidget(self.widget_7)
        self.process_shot.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.process_shot.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.process_shot.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.process_shot.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.process_shot.setObjectName("process_shot")
        self.process_shot.setColumnCount(4)
        self.process_shot.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.process_shot.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_shot.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_shot.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_shot.setHorizontalHeaderItem(3, item)
        self.process_shot.horizontalHeader().setDefaultSectionSize(50)
        self.process_shot.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.process_shot)
        self.process_line = QtWidgets.QLineEdit(self.widget_7)
        self.process_line.setObjectName("process_line")
        self.verticalLayout.addWidget(self.process_line)
        self.process_bolck = QtWidgets.QPushButton(self.widget_7)
        self.process_bolck.setObjectName("process_bolck")
        self.verticalLayout.addWidget(self.process_bolck)
        self.process_withdraw = QtWidgets.QPushButton(self.widget_7)
        self.process_withdraw.setObjectName("process_withdraw")
        self.verticalLayout.addWidget(self.process_withdraw)
        self.process_wake = QtWidgets.QPushButton(self.widget_7)
        self.process_wake.setObjectName("process_wake")
        self.verticalLayout.addWidget(self.process_wake)
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(self.groupBox)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.process_graph = QtWidgets.QTableWidget(self.widget_6)
        self.process_graph.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.process_graph.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.process_graph.setObjectName("process_graph")
        self.process_graph.setColumnCount(0)
        self.process_graph.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.process_graph.setVerticalHeaderItem(9, item)
        self.process_graph.horizontalHeader().setVisible(False)
        self.process_graph.verticalHeader().setVisible(True)
        self.verticalLayout_6.addWidget(self.process_graph)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_10 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.device_shot = QtWidgets.QTableWidget(self.widget_10)
        self.device_shot.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.device_shot.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.device_shot.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.device_shot.setObjectName("device_shot")
        self.device_shot.setColumnCount(3)
        self.device_shot.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.device_shot.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.device_shot.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.device_shot.setHorizontalHeaderItem(2, item)
        self.device_shot.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.device_shot)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.device_line = QtWidgets.QLineEdit(self.widget_3)
        self.device_line.setObjectName("device_line")
        self.horizontalLayout_2.addWidget(self.device_line)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.device_add = QtWidgets.QPushButton(self.widget_4)
        self.device_add.setObjectName("device_add")
        self.horizontalLayout.addWidget(self.device_add)
        self.device_del = QtWidgets.QPushButton(self.widget_4)
        self.device_del.setObjectName("device_del")
        self.horizontalLayout.addWidget(self.device_del)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.file_pwd = QtWidgets.QLabel(self.widget_9)
        self.file_pwd.setText("")
        self.file_pwd.setObjectName("file_pwd")
        self.verticalLayout_4.addWidget(self.file_pwd)
        self.file_shot = QtWidgets.QTableWidget(self.widget_9)
        self.file_shot.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_shot.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.file_shot.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.file_shot.setObjectName("file_shot")
        self.file_shot.setColumnCount(2)
        self.file_shot.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_shot.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_shot.setHorizontalHeaderItem(1, item)
        self.file_shot.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.file_shot)
        self.run = QtWidgets.QPushButton(self.widget_9)
        self.run.setObjectName("run")
        self.verticalLayout_4.addWidget(self.run)
        self.file_line = QtWidgets.QLineEdit(self.widget_9)
        self.file_line.setObjectName("file_line")
        self.verticalLayout_4.addWidget(self.file_line)
        self.widget_11 = QtWidgets.QWidget(self.widget_9)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.file_rename = QtWidgets.QPushButton(self.widget_11)
        self.file_rename.setObjectName("file_rename")
        self.gridLayout_3.addWidget(self.file_rename, 1, 0, 1, 1)
        self.file_write = QtWidgets.QPushButton(self.widget_11)
        self.file_write.setObjectName("file_write")
        self.gridLayout_3.addWidget(self.file_write, 1, 1, 1, 1)
        self.file_fresh = QtWidgets.QPushButton(self.widget_11)
        self.file_fresh.setObjectName("file_fresh")
        self.gridLayout_3.addWidget(self.file_fresh, 3, 0, 1, 1)
        self.file_mkdir = QtWidgets.QPushButton(self.widget_11)
        self.file_mkdir.setObjectName("file_mkdir")
        self.gridLayout_3.addWidget(self.file_mkdir, 2, 0, 1, 1)
        self.file_del = QtWidgets.QPushButton(self.widget_11)
        self.file_del.setObjectName("file_del")
        self.gridLayout_3.addWidget(self.file_del, 3, 1, 1, 1)
        self.file_vi = QtWidgets.QPushButton(self.widget_11)
        self.file_vi.setObjectName("file_vi")
        self.gridLayout_3.addWidget(self.file_vi, 2, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.horizontalLayout_4.addWidget(self.widget_9)
        self.widget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.file_graph = QtWidgets.QTableWidget(self.widget_5)
        self.file_graph.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_graph.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.file_graph.setObjectName("file_graph")
        self.file_graph.setColumnCount(0)
        self.file_graph.setRowCount(0)
        self.file_graph.horizontalHeader().setVisible(False)
        self.file_graph.horizontalHeader().setMinimumSectionSize(1)
        self.file_graph.verticalHeader().setVisible(False)
        self.file_graph.verticalHeader().setMinimumSectionSize(1)
        self.verticalLayout_7.addWidget(self.file_graph)
        self.horizontalLayout_4.addWidget(self.widget_5)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Doors OS"))
        self.groupBox_3.setTitle(_translate("MainWindow", "内存"))
        self.label_3.setText(_translate("MainWindow", "内存空间状态"))
        self.label_9.setText(_translate("MainWindow", "总空间："))
        self.label_5.setText(_translate("MainWindow", "统计信息"))
        self.label_12.setText(_translate("MainWindow", "已用空间："))
        self.groupBox.setTitle(_translate("MainWindow", "进程管理"))
        self.label_2.setText(_translate("MainWindow", "进程名称："))
        item = self.process_shot.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "进程"))
        item = self.process_shot.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "优先"))
        item = self.process_shot.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "pid"))
        item = self.process_shot.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "状态"))
        self.process_bolck.setText(_translate("MainWindow", "阻塞"))
        self.process_withdraw.setText(_translate("MainWindow", "撤销"))
        self.process_wake.setText(_translate("MainWindow", "唤醒"))
        self.label_6.setText(_translate("MainWindow", "进程快照"))
        item = self.process_graph.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.process_graph.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.process_graph.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.process_graph.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.process_graph.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.process_graph.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.process_graph.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "8"))
        item = self.process_graph.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.process_graph.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.process_graph.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        self.groupBox_4.setTitle(_translate("MainWindow", "设备管理"))
        item = self.device_shot.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "设备"))
        item = self.device_shot.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "状态"))
        item = self.device_shot.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "中断"))
        self.label.setText(_translate("MainWindow", "设备名称："))
        self.device_add.setText(_translate("MainWindow", "插入设备"))
        self.device_del.setText(_translate("MainWindow", "弹出设备"))
        self.groupBox_2.setTitle(_translate("MainWindow", "文件系统"))
        item = self.file_shot.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名称"))
        item = self.file_shot.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型"))
        self.run.setText(_translate("MainWindow", "运行"))
        self.file_rename.setText(_translate("MainWindow", "重命名"))
        self.file_write.setText(_translate("MainWindow", "写入"))
        self.file_fresh.setText(_translate("MainWindow", "刷新"))
        self.file_mkdir.setText(_translate("MainWindow", "新建目录"))
        self.file_del.setText(_translate("MainWindow", "删除"))
        self.file_vi.setText(_translate("MainWindow", "新建文件"))
        self.label_7.setText(_translate("MainWindow", "硬盘映射"))
        self.menu.setTitle(_translate("MainWindow", "选项"))

